---
title: "final-project"
output: pdf_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```

```{r data}

data <- readxl::read_xlsx("data/41304_2018_149_MOESM2_ESM (1).xlsx")

# This was to make viewing the countries on the list easier. 

y2000 <- data %>%
  filter(year == "2000")
view(y2000)

# This makes regression across the government types easier. 

data <- data %>%
  mutate(parliamentarism = ifelse(regimenarrowcat == 0, 1, 0),
         semipresidentialism = ifelse(regimenarrowcat == 1, 1, 0),
         presidentialism = ifelse(regimenarrowcat == 2, 1, 0),
         semimonarchy = ifelse(regimenarrowcat == 3, 1, 0),
         singleparty = ifelse(regimenarrowcat == 4, 1, 0),
         multipartyauthoritarian = ifelse(regimenarrowcat == 5, 1, 0),
         personalist = ifelse(regimenarrowcat == 6, 1, 0),
         military = ifelse(regimenarrowcat == 7, 1, 0),
         absolutemonarchy = ifelse(regimenarrowcat == 8, 1, 0),
         monarchicoligarchy = ifelse(regimenarrowcat == 9, 1, 0),
         otheroligarchy = ifelse(regimenarrowcat == 10, 1, 0),
         missing = ifelse(regimenarrowcat == 99, 1, 0))

# This allows for an easier geographic perspective. 

data <- data %>%
  mutate(asian = ifelse(
    ccode >= 630, 1, 0),
    african = ifelse(
      ccode >= 402 & ccode < 630, 1, 0),
    european = ifelse(
      ccode >= 200 & ccode <= 395, 1, 0),
    american = ifelse(
      ccode >= 2 & ccode < 200, 1, 0))



```

```{r ussr}

data_ussr <- data %>%
  mutate(year_new = year - 1900) %>%
  filter(year_new > 17) %>%
  select(year_new, singleparty)

lm_ussr <- lm(singleparty ~ year_new, data = data_ussr)

summary(lm_ussr)$adj.r.squared

data_ussr_alt <- data %>%
  mutate(year_new = year - 1900) %>%
  filter(year_new > 50) %>%
  select(year_new, singleparty)

lm_ussr_alt <- lm(singleparty ~ year_new, data = data_ussr_alt)

summary(lm_ussr_alt)$adj.r.squared

# The alt was designed to better compare with ussr2

data_ussr2 <- data %>%
  mutate(year_new = year - 1900) %>%
  filter(year_new > 17, european == 1) %>%
  select(year_new, singleparty)

lm_ussr2 <- lm(singleparty ~ year_new, data = data_ussr2)

lm_ussr2_sq <- lm(singleparty ~ year_new +
                    I(year_new^2), data = data_ussr2)

summary(lm_ussr2)$adj.r.squared

summary(lm_ussr2_sq)$adj.r.squared

# First regression includes all countries, second only includes Europe. 

data_ussr3 <- data %>%
  mutate(year_new = year - 1900) %>%
  filter(year_new > 50, european == 1) %>%
  select(year_new, singleparty)

lm_ussr3 <- lm(singleparty ~ year_new, data = data_ussr3)

lm_ussr3_sq <- lm(singleparty ~ year_new +
                    I(year_new^2), data = data_ussr3)

summary(lm_ussr3)$adj.r.squared

summary(lm_ussr3_sq)$adj.r.squared

data_ussr3_alt <- data %>%
  mutate(year_new = year - 1900) %>%
  filter(year_new > 50, european == 1 | asian == 1) %>%
  select(year_new, singleparty)

lm_ussr3_alt <- lm(singleparty ~ year_new, data = data_ussr3_alt)

lm_ussr3_alt_sq <- lm(singleparty ~ year_new +
                    I(year_new^2), data = data_ussr3_alt)

summary(lm_ussr3_alt)$adj.r.squared

summary(lm_ussr3_alt_sq)$adj.r.squared

# Third regression changes the baseline year. 

data_ussr4 <- data %>%
  mutate(year_new = year - 1900) %>%
  filter(year_new > 75, european == 1) %>%
  select(year_new, singleparty)

lm_ussr4 <- lm(singleparty ~ year_new, data = data_ussr4)

summary(lm_ussr4)$adj.r.squared

data_ussr5 <- data %>%
  mutate(year_new = year - 1900) %>%
  filter(year_new > 87, european == 1) %>%
  select(year_new, singleparty)

lm_ussr5 <- lm(singleparty ~ year_new, data = data_ussr5)

summary(lm_ussr5)$adj.r.squared

# The fourth and fifth regressions also change baseline year.

# Interestingly, the correlation shifts significantly over time. 

ggplot(data = data_ussr, mapping = aes(x = year_new, y = singleparty)) +
  geom_col(aes(y = singleparty)) +
  geom_abline(intercept = .1431769 * 30, slope = -0.0006335 * 30)

```

```{r china}

data_china <- data %>%
  mutate(year_new = year - 1900) %>%
  filter(year_new > 49) %>%
  select(year_new, singleparty)

lm_china <- lm(singleparty ~ year_new, data = data_china)

summary(lm_china)$adj.r.squared

data_china2 <- data %>%
  mutate(year_new = year - 1900) %>%
  filter(year_new > 49, asian == 1) %>%
  select(year_new, singleparty)

lm_china2 <- lm(singleparty ~ year_new, data = data_china2)

summary(lm_china2)$adj.r.squared

data_china3 <- data %>%
  mutate(year_new = year - 1900) %>%
  filter(year_new > 75, asian == 1) %>%
  select(year_new, singleparty)

lm_china3 <- lm(singleparty ~ year_new, data = data_china3)

summary(lm_china3)$adj.r.squared


``` 





